const database = [
    { id: 1, category: "Corporate", author: "Achyuta Narayanan", date: "May 1, 2026", title: "Navigating M&A Deal Structures", excerpt: "A breakdown of cross-border mergers and regulatory hurdles.", content: "When analyzing cross-border Mergers and Acquisitions in 2026, the primary hurdle remains regulatory compliance. \n\nInterns looking to excel in corporate law must understand the difference between asset purchases and stock purchases..." },
    { id: 2, category: "Corporate", author: "Amishee Gupta", date: "April 28, 2026", title: "The Rise of ESG in Boardrooms", excerpt: "Why environmental, social, and governance metrics dictate corporate deals.", content: "ESG is no longer a buzzword. It is a strict legal requirement for publicly traded companies. \n\nLawyers are now tasked with auditing supply chains to ensure compliance with the new sustainability directives..." },
    { id: 3, category: "Corporate", author: "Navya Arun", date: "April 25, 2026", title: "FEMA Regulations for Tech Startups", excerpt: "Foreign Direct Investment limits and compliance for Indian unicorns.", content: "For a tech startup raising capital from foreign venture capitalists, strict adherence to the Foreign Exchange Management Act (FEMA) is critical. \n\nPenalties for non-compliance can severely disrupt funding rounds..." },
    
    { id: 4, category: "Tax", author: "Intern Rahul", date: "May 2, 2026", title: "GST Implications on Digital Assets", excerpt: "How the revenue department views crypto and digital tokens.", content: "The taxation of digital assets remains a grey area. However, recent circulars indicate a strict 28% GST on all utility tokens. \n\nThis article breaks down the recent tribunal ruling and its impact on Web3 startups." },
    { id: 5, category: "Tax", author: "Intern Priya", date: "April 20, 2026", title: "Direct Tax Code: What Changed?", excerpt: "A simplified guide to the new personal income tax slabs.", content: "The recent budget introduced sweeping changes to the Direct Tax Code. \n\nThe old regime is officially being phased out, forcing taxpayers to optimize their investments differently..." },
    { id: 6, category: "Tax", author: "Intern Ankit", date: "April 15, 2026", title: "Corporate Tax Evasion Loopholes", excerpt: "Analyzing the landmark Supreme Court ruling on shell companies.", content: "The lifting of the corporate veil has become a standard procedure for the IT Department when investigating shell corporations registered in tax havens..." },
    
    { id: 7, category: "ADR", author: "Radhini Thalavai", date: "April 30, 2026", title: "Challenging Arbitral Awards", excerpt: "Recent procedural shifts under Section 34 of the Act.", content: "The scope of judicial intervention in domestic arbitration is intentionally narrow. \n\nHowever, 'patent illegality' remains the most utilized ground for setting aside an award under Section 34..." },
    { id: 8, category: "ADR", author: "Intern Sneha", date: "April 18, 2026", title: "Mediation Act 2026: A Review", excerpt: "How mandatory pre-litigation mediation is changing commercial disputes.", content: "Before approaching commercial courts, parties are now mandated to exhaust mediation. \n\nThis has drastically reduced the burden on the judiciary but requires lawyers to develop strong negotiation skills..." },
    { id: 9, category: "ADR", author: "Intern Dev", date: "April 10, 2026", title: "International Commercial Arbitration", excerpt: "Choosing the right seat: Singapore vs. London.", content: "The 'Seat' of arbitration determines the supervisory jurisdiction of the courts. \n\nFor Indian parties, SIAC (Singapore) has emerged as the preferred destination over traditional venues like London..." },
    
    { id: 10, category: "Litigation", author: "Radhini Thalavai", date: "May 1, 2026", title: "The Art of Cross-Examination", excerpt: "Essential techniques for junior advocates in trial courts.", content: "Cross-examination is an art, not a science. A junior advocate must learn never to ask a question to which they do not already know the answer. \n\nPreparation of the witness and studying the CrPC is paramount..." },
    { id: 11, category: "Litigation", author: "Intern Rohan", date: "April 22, 2026", title: "Bail Jurisprudence in India", excerpt: "Analyzing the 'Bail is rule, jail is exception' doctrine.", content: "Despite the Supreme Court's repeated emphasis, trial courts often act conservatively when granting bail in high-profile cases. \n\nThis article examines recent precedents under the PMLA framework..." },
    { id: 12, category: "Litigation", author: "Intern Maya", date: "April 12, 2026", title: "Writ Petitions under Article 226", excerpt: "When to approach the High Court vs. Alternate Remedies.", content: "The High Court's extraordinary jurisdiction under Article 226 is a powerful tool. \n\nHowever, courts will dismiss petitions if an efficacious alternative statutory remedy exists..." },
    
    { id: 13, category: "Family Law", author: "Intern Kabir", date: "May 3, 2026", title: "Mutual Consent Divorce Procedures", excerpt: "The waiver of the 6-month cooling-off period.", content: "The Supreme Court has clarified that the 6-month statutory waiting period for mutual consent divorce under the Hindu Marriage Act is not mandatory, but directory. \n\nFamily courts can waive it under specific circumstances..." },
    { id: 14, category: "Family Law", author: "Intern Riya", date: "April 26, 2026", title: "Child Custody and Welfare", excerpt: "How courts determine the 'best interests of the child'.", content: "In custody battles, the financial superiority of one parent does not guarantee custody. \n\nThe paramount consideration for any family court is the emotional and psychological welfare of the child..." },
    { id: 15, category: "Family Law", author: "Intern Aisha", date: "April 14, 2026", title: "Inheritance Rights of Daughters", excerpt: "A decade after the Vineeta Sharma judgement.", content: "The amendment to the Hindu Succession Act gave daughters equal coparcenary rights. \n\nWe analyze how this is currently being executed in partition suits across district courts..." }
];
